apiVersion: v1
kind: Secret
metadata:
  name: google-secret
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: 633958932993-hefmpm2lrcaa9rk7on03j6b7a8p8t1dl.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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